#ifndef CONFIG_H
#define CONFIG_H

#define MATRIX_ROWS 5
#define MATRIX_COLS 12

#define TAPPING_TERM 200

#define ENCODERS_PAD_A { GP14 }
#define ENCODERS_PAD_B { GP15 }

#define ENCODER_RESOLUTIONS { 4 }

#define WS2812_DI_PIN GP25
#define DRIVER_LED_TOTAL 50
#define RGB_MATRIX_LED_COUNT 50
#define RGBLED_NUM 50

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500

#endif
